config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sepia-hyena.sh
        container: qc.acc_stinky-corn-lionfish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-burgundy-horse.sh
        container: qc.doc_breezy-cerise-raccoon
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-lilac-saola.sh
        container: qc.doc_ready-cream-ferret
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-amber-molly.sh
        container: qc.doc_stuffy-heliotrope-schnauzer
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-brass-coati.sh
        container: qc.lic_stinky-cornflower-warthog
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chartreuse-dog.sh
        container: qc.sty_nippy-mustard-quokka
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-linen-molly.sh
        container: qc.ver_scummy-cream-bracke
timeout: 5400
