config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.12
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-blue-hedgehog.sh
        container: qc.acc_thirsty-saffron-squid
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-buff-centipede.sh
        container: qc.doc_greasy-lavender-wolfhound
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-thistle-sloth.sh
        container: qc.doc_gloppy-chocolate-toad
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pumpkin-husky.sh
        container: qc.doc_sloppy-eggplant-rhinoceros
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-eggplant-pinscher.sh
        container: qc.lic_flimsy-scarlet-hound
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-chestnut-foxhound.sh
        container: qc.sty_squeaky-amaranth-chihuahua
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cream-cuscus.sh
        container: qc.ver_skanky-cinnamon-llama
timeout: 5400
