config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-salmon-lemur.sh
        container: qc.acc_skimpy-cornflower-coati
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-peach-birman.sh
        container: qc.doc_dorky-rust-dog
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-charcoal-goose.sh
        container: qc.doc_dorky-pear-wildebeest
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-sangria-chow.sh
        container: qc.doc_scaly-emerald-starfish
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cinnabar-akita.sh
        container: qc.lic_seedy-chocolate-angelfish
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-chartreuse-ladybird.sh
        container: qc.sty_pokey-black-chinook
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-taupe-crane.sh
        container: qc.ver_cranky-tangerine-sheep
timeout: 5400
