config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.12
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-smalt-chin.sh
        container: qc.acc_woolly-carmine-burmese
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-wheat-vulture.sh
        container: qc.doc_frumpy-linen-shrew
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-thistle-beagle.sh
        container: qc.doc_wimpy-chestnut-bombay
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-auburn-husky.sh
        container: qc.doc_blurry-denim-ocelot
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-azure-koala.sh
        container: qc.lic_stinky-linen-seal
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-harlequin-gibbon.sh
        container: qc.sty_scummy-alizarin-loon
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-amber-mist.sh
        container: qc.ver_sickly-sangria-donkey
timeout: 5400
