config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cornflower-koala.sh
        container: qc.acc_hazy-razzmatazz-barb
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-flax-barnacle.sh
        container: qc.doc_cozy-silver-maltese
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-vermilion-squirt.sh
        container: qc.doc_tacky-platinum-raccoon
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cinnabar-jackal.sh
        container: qc.doc_gummy-linen-toad
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-smalt-lemming.sh
        container: qc.lic_ugly-plum-chimpanzee
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-flax-peccary.sh
        container: qc.sty_chewy-ruby-discus
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gamboge-macaque.sh
        container: qc.ver_queasy-olivine-iguana
timeout: 5400
