config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-teal-affenpinscher.sh
        container: qc.acc_muzzy-periwinkle-cattle
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-olive-caracal.sh
        container: qc.doc_ugly-cream-discus
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-rust-woodlouse.sh
        container: qc.doc_gimpy-cardinal-panda
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sangria-grasshopper.sh
        container: qc.doc_woolly-olivine-drever
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cobalt-rat.sh
        container: qc.lic_frumpy-turquoise-wombat
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-olive-indri.sh
        container: qc.sty_hazy-ochre-kangaroo
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cornflower-ostrich.sh
        container: qc.ver_chewy-pumpkin-toad
timeout: 5400
